### PR TITLE
Issues/10 uskill localization

### PR DESCRIPTION
**Pull request by deidril**
system.json and fr.json have been converted to utf-8. Otherwhile french special characters won't be printed.

### CODE REVIEW

**Review by n0q — CHANGES_REQUESTED** [review]
Hey, nice work. This will need a few changes, though.

- Your language file is missing a proper path in system.json (lang/fr.json would make this function).

- The system itself will not load with this system.json, as it is not not just UTF-8, but UTF-8 with a byte order mark.

UTF-8 is fine, UTF-8 BOM is making foundry choke and not load the system, so you'll need to get rid of the BOM. Preferably do the same with fr.json, which is also UTF-8 BOM. It's not causing an issue, but maybe later. It's interesting this loads on your system but not mine, and I wonder if that's some sort of foundry bug.

- You'll need to change how chatmgr.js is handling skills, as it doesn't know to localize yet, either.

image

Fix this stuff, and this seems fine to merge.

**Comment by deidril** [comment]
Thank for the quick review.
I did the changes. I switched editor to visual code, which will be better for utf8 issues.

**Comment by n0q** [comment]
Nice. I'll re-review this later today. Good job!

**Comment by n0q** [comment]
Looks good!

**Pull request merged**
